server:
  port: 8080

spring:
  r2dbc:
    url: ${R2DB_URL:r2dbc:postgresql://localhost:5432/testdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/testdb}
    user: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: market-app-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET:market-app-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/market-realm/protocol/openid-connect/token}

logging:
  level:
    com.my.project.mymarketapp: INFO
    org.springframework.web: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG

cache:
  item:
    ttl-minutes: ${CACHE_TTL_MINUTES:2}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8081}
