services:
  postgres:
    image: postgres:16
    container_name: postgres-db-my-market
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-my-market
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      PAYMENT_INITIAL_BALANCE: 100000

  market-app:
    build:
      context: .
      dockerfile: market-app/Dockerfile
    container_name: my-market-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/testdb
      R2DB_URL: r2dbc:postgresql://postgres:5432/testdb
      DB_USERNAME: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PAYMENT_SERVICE_URL: http://payment-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
