services:
  postgres:
    image: postgres:16
    container_name: postgres-db-my-market
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: my-market-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/testdb
      R2DB_URL: r2dbc:postgresql://postgres:5432/testdb
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
