server:
  port: 8080

spring:
  r2dbc:
    url: ${R2DB_URL:r2dbc:postgresql://localhost:5432/testdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/testdb}
    user: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}

logging:
  level:
    com.my.project.mymarketapp: INFO
    org.springframework.web: INFO
    org.springframework.r2dbc: DEBUG
